; PlatformIO Configuration for ErdfeuchteSensor
; Board: M5Stamp C3 (ESP32-C3)

[env:m5stamp-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
